# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQP_M5sZoE876dK9jsaQz0aMbLt0r2v2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')

# Charger les données
df = pd.read_csv('Mall_Customers.csv')
print("Dimensions du dataset :", df.shape)
print("\nPremières lignes :")
print(df.head())
print("\nInformations sur les données :")
print(df.info())

print("Valeurs manquantes par colonne :")
print(df.isnull().sum())

# Si valeurs manquantes, les traiter
# df = df.dropna()  # Supprimer les lignes avec valeurs manquantes
# ou
# df['colonne'] = df['colonne'].fillna(df['colonne'].mean())  # Remplacer par la moyenne

# Statistiques descriptives
print("\nStatistiques descriptives :")
print(df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].describe())

# Histogrammes
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.histplot(df['Age'], kde=True, bins=15)
plt.title('Distribution de l\'Âge')

plt.subplot(1, 3, 2)
sns.histplot(df['Annual Income (k$)'], kde=True, bins=15)
plt.title('Distribution du Revenu Annuel')

plt.subplot(1, 3, 3)
sns.histplot(df['Spending Score (1-100)'], kde=True, bins=15)
plt.title('Distribution du Score de Dépense')

plt.tight_layout()
plt.show()

# Analyse par genre
print("\nRépartition par genre :")
print(df['Gender'].value_counts())

plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
sns.boxplot(x='Gender', y='Age', data=df)
plt.title('Âge par Genre')

plt.subplot(1, 3, 2)
sns.boxplot(x='Gender', y='Annual Income (k$)', data=df)
plt.title('Revenu par Genre')

plt.subplot(1, 3, 3)
sns.boxplot(x='Gender', y='Spending Score (1-100)', data=df)
plt.title('Score de Dépense par Genre')

plt.tight_layout()
plt.show()

# Justification du choix des variables

print("""
Justification du choix des variables :
- Age : Influence les habitudes d'achat
- Annual Income (k$) : Capacité financière du client
- Spending Score (1-100) : Comportement de dépense
- CustomerID et Gender ne sont pas utilisés pour le clustering
""")

variables_clustering = ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']
X = df[variables_clustering]

print("Variables sélectionnées pour le clustering :")
print(variables_clustering)

# Standardisation des données (important pour K-Means)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Création d'un DataFrame avec les données standardisées
X_scaled_df = pd.DataFrame(X_scaled, columns=variables_clustering)
print("\nDonnées standardisées (premières 5 lignes) :")
print(X_scaled_df.head())

print("\nStatistiques après standardisation :")
print(X_scaled_df.describe())

"""Partie 2 - Analyse exploratoire

"""

# Pairplot pour voir toutes les relations
print("Création du pairplot...")
sns.pairplot(df[variables_clustering])
plt.suptitle('Relations entre les variables de clustering', y=1.02)
plt.show()

# Heatmap de corrélation
plt.figure(figsize=(8, 6))
correlation_matrix = df[variables_clustering].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Matrice de corrélation entre variables')
plt.show()

print("Matrice de corrélation :")
print(correlation_matrix)

# Scatter plots pour identifier des regroupements visuels
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Revenu vs Score de dépense
axes[0].scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'], alpha=0.6, c='blue')
axes[0].set_xlabel('Revenu Annuel (k$)')
axes[0].set_ylabel('Score de Dépense')
axes[0].set_title('Revenu vs Score de Dépense')

# Âge vs Score de dépense
axes[1].scatter(df['Age'], df['Spending Score (1-100)'], alpha=0.6, c='green')
axes[1].set_xlabel('Âge')
axes[1].set_ylabel('Score de Dépense')
axes[1].set_title('Âge vs Score de Dépense')

# Âge vs Revenu
axes[2].scatter(df['Age'], df['Annual Income (k$)'], alpha=0.6, c='red')
axes[2].set_xlabel('Âge')
axes[2].set_ylabel('Revenu Annuel (k$)')
axes[2].set_title('Âge vs Revenu')

plt.tight_layout()
plt.show()

# Analyse visuelle pour émettre des hypothèses
print("""
Hypothèses sur le nombre de segments basées sur l'analyse exploratoire :

1. Revenu vs Score de Dépense : On distingue environ 5 groupes naturels
   - Clients à revenu faible et dépenses faibles
   - Clients à revenu faible et dépenses élevées
   - Clients à revenu moyen et dépenses moyennes
   - Clients à revenu élevé et dépenses faibles
   - Clients à revenu élevé et dépenses élevées

2. Âge vs Score de Dépense : On voit des regroupements par tranche d'âge

Hypothèse initiale : 3 à 6 clusters semblent appropriés
""")

"""Partie 3 - Application de K-Means

"""

# Méthode du coude
inertia = []
k_range = range(2, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Graphique de la méthode du coude
plt.figure(figsize=(10, 6))
plt.plot(k_range, inertia, 'bo-')
plt.xlabel('Nombre de clusters (k)')
plt.ylabel('Inertie')
plt.title('Méthode du Coude pour la sélection de k')
plt.xticks(k_range)
plt.grid(True)
plt.show()

# Calcul des scores de silhouette
silhouette_scores = []
for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    cluster_labels = kmeans.fit_predict(X_scaled)
    silhouette_avg = silhouette_score(X_scaled, cluster_labels)
    silhouette_scores.append(silhouette_avg)
    print(f"Pour k={k}, score de silhouette: {silhouette_avg:.4f}")

# Graphique des scores de silhouette
plt.figure(figsize=(10, 6))
plt.plot(k_range, silhouette_scores, 'ro-')
plt.xlabel('Nombre de clusters (k)')
plt.ylabel('Score de Silhouette')
plt.title('Scores de Silhouette pour différents k')
plt.xticks(k_range)
plt.grid(True)
plt.show()

# Choix du k optimal (exemple avec k=5)

k_optimal = 5
kmeans_final = KMeans(n_clusters=k_optimal, random_state=42)
df['Cluster'] = kmeans_final.fit_predict(X_scaled)

print(f"Modèle final entraîné avec k={k_optimal}")
print("Répartition des clusters :")
print(df['Cluster'].value_counts().sort_index())

"""Partie 4 - Interprétation

"""

# Statistiques par cluster

cluster_profile = df.groupby('Cluster')[variables_clustering].mean()
cluster_profile['Count'] = df.groupby('Cluster').size()

print("Profil moyen par cluster :")
print(cluster_profile)

# Analyse détaillée de chaque cluster

for cluster in range(k_optimal):
    cluster_data = df[df['Cluster'] == cluster]
    print(f"\n--- Cluster {cluster} ---")
    print(f"Nombre de clients: {len(cluster_data)}")
    print(f"Âge moyen: {cluster_data['Age'].mean():.1f} ans")
    print(f"Revenu moyen: {cluster_data['Annual Income (k$)'].mean():.1f} k$")
    print(f"Score de dépense moyen: {cluster_data['Spending Score (1-100)'].mean():.1f}")

# Exemple de noms basés sur les caractéristiques

segment_names = {
    0: "Jeunes à revenu moyen et dépenses modérées",
    1: "Jeunes à haut revenu et fortes dépenses",
    2: "Clients âgés à revenu moyen et faibles dépenses",
    3: "Adultes à revenu moyen et dépenses élevées",
    4: "Jeunes à faible revenu et fortes dépenses"
}

df['Segment'] = df['Cluster'].map(segment_names)

# Visualisation 2D

plt.figure(figsize=(12, 8))
scatter = plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'],
                     c=df['Cluster'], cmap='viridis', alpha=0.7)
plt.colorbar(scatter)
plt.xlabel('Revenu Annuel (k$)')
plt.ylabel('Score de Dépense (1-100)')
plt.title('Segmentation Client - K-Means Clusters')

print("Segment names:", segment_names)

for i, segment in segment_names.items():
    cluster_data = df[df['Cluster'] == i]
    if len(cluster_data) > 0:
        x_pos = cluster_data['Annual Income (k$)'].mean()
        y_pos = cluster_data['Spending Score (1-100)'].mean()
        plt.text(x_pos, y_pos, segment, fontsize=9, ha='center',
                bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))

plt.grid(True, alpha=0.3)
plt.show()

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_scaled)

print("Comparaison DBSCAN vs K-Means:")
print(f"Nombre de clusters DBSCAN: {len(set(dbscan_labels))}")
print(f"Nombre de clusters K-Means: {k_optimal}")

print("\n=== RECOMMANDATIONS BUSINESS ===")
for cluster, segment_name in segment_names.items():
    cluster_data = df[df['Cluster'] == cluster]
    print(f"\nSegment: {segment_name}")
    print(f"- Taille: {len(cluster_data)} clients")
    print(f"- Caractéristiques: Âge {cluster_data['Age'].mean():.1f} ans, "
          f"Revenu {cluster_data['Annual Income (k$)'].mean():.1f} k$, "
          f"Dépenses {cluster_data['Spending Score (1-100)'].mean():.1f}")